# Generated by Django 4.2.9 on 2024-08-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_be_contacted',
            new_name='allows_data_sharing',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='can_data_be_shared',
            new_name='is_contactable',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
