# Generated by Django 4.2.9 on 2024-08-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_can_be_contacted_user_allows_data_sharing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allows_data_sharing',
            new_name='can_be_contacted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_contactable',
            new_name='can_data_be_shared',
        ),
    ]
